[build]
builder = "heroku/buildpacks:20"

[deploy]
startCommand = "java -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=$PORT -jar target/route-optimization-1.0.0-SNAPSHOT-runner.jar"

[environments.production]
variables = { QUARKUS_HTTP_PORT = "$PORT" }